### ISSUE TITLE
Test faalt na 15 December

### ISSUE THREAD

**Issue by gglerum** [KumaSan9319/TaskManager#1]
https://github.com/KumaSan9319/TaskManager/blob/d48dd76316e5b9e82b49fcc9778b1b0f69ddd526/src/test/java/tasks/ManageableTest.java#L15

Als je werkt met data die in de toekomst liggen, dan kun je het beste met `LocalDate.now()` en de `plusDays()` method werken.

```LocalDate.now().plusDays(2)```

Geeft een LocalDate object terug dat twee dagen in de toekomst ligt.

**Comment by KumaSan9319** [comment]
In hindsight was die test inderdaad wat kortzichtig geschreven hahaha. Ik heb het aangepast
