### ISSUE TITLE
Declareer variabelen waar het kan met een Interface

### ISSUE THREAD

**Issue by gglerum** [KumaSan9319/TaskManager#2]
https://github.com/KumaSan9319/TaskManager/blob/d48dd76316e5b9e82b49fcc9778b1b0f69ddd526/src/test/java/tasks/ListTest.java#L12

`List<Manageable>` ipv `ArrayList<Manageable>`. Je kunt dan in de toekomst altijd van type list wisselen.

**Comment by KumaSan9319** [comment]
Ik liep dus tegen een probleem aan waar IntelliJ mij niet Lists wou laten initiëren als Lists. Ik kreeg errors. Ik ben er onderhand achter dat dat was omdat ik ook een class genaamd List heb en hij daardoor in de war raakte. Ik heb mijn List class gerenamed naar Catalogue en alle instances van Arraylist veranderd naar List.
