### ISSUE TITLE
Code Analysis geeft 16 errors terug

### ISSUE THREAD

**Issue by gglerum** [KumaSan9319/TaskManager#7]
Als je in Intellij op je project map gaat staan, rechts klikken: `Analyze -> Inspect` en dan kiezen voor `whole project`.

Kijk of je deze fouten allemaal op kunt lossen. Van een aantal had ik al issues gemaakt.

**Comment by KumaSan9319** [comment]
Deze functionaliteit van IntelliJ had ik nog niet eerder gezien. Ik heb al de 16 warnings op 1 na weggewerkt. Hij wil nog steeds dat ik een instance field in Project final maak terwijl die nog zeker wel aangepast wordt met methods in die class. Die field heb ik voorlopig dus gehouden zoals hij is.
